// <auto-generated />
namespace Chopwella.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class staffnumedited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(staffnumedited));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291821263_staffnumedited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
